name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: MyReleaseMessage

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          echo "## Release Notes" >> release_notes.md
          git log --pretty=format:"- %s" ${GITHUB_REF#refs/*/}...HEAD >> release_notes.md
          echo "::set-output name=release_notes::$(cat release_notes.md)"
        shell: bash
