name: Auto Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 24th July 2021: AdoptOpenJDK was moved to the Eclipse Foundation and rebranding.
          java-version: '17'

#      - name: Build project
#        run: mvn clean package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          echo "## Release Notes" >> release_notes.md
          git log --pretty=format:"- %s" ${GITHUB_REF#refs/*/}...HEAD >> release_notes.md
          echo "::set-output name=release_notes::$(cat release_notes.md)"
        shell: bash
