name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
    paths-ignore:
    - 'CHANGELOG.md'
  # pull_request event is required only for autolabeler
#  pull_request:
#    # Only following types are handled by the action, but one can default to all as well
#    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 24th July 2021: AdoptOpenJDK was moved to the Eclipse Foundation and rebranding.
          java-version: '17'

      - name: Get current version without snapshot
        id: version-to-release
        run: |
          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d- -f1)
          echo "::set-output name=TAG_NAME::$version"

      - name: Print current version
        run: echo "Current version to release ${{ steps.version-to-release.outputs.TAG_NAME }}"

      - name: Set branch tag
        id: masterVars
        run: |
          export TAG_FROM_REF=${GITHUB_REF#refs/*/}
          IMAGE_TAG=$(echo $TAG_FROM_REF | tr -d v)
          echo "::set-output name=branch_tag::$IMAGE_TAG"

      - name: Set git email
        run: git config --global user.email "githubaction@modusbox.com"
      - name: Set git name
        run: git config --global user.name "modusbox_builder"

      - name: Prepare release to increment pom version and create tag
        id: mvn-prepare-release
        env:
          RELEASE_TAG: ${{ steps.version-to-release.outputs.TAG_NAME  }}
        run: mvn clean -DskipTests --batch-mode -Dtag=$RELEASE_TAG -Darguments=-DskipTests release:prepare

      - name: The prepare-release step has failed
        if: ${{ failure() && steps.mvn-prepare-release.conclusion == 'failure'}}
        run: mvn release:rollback


  update-changelog:
    uses: jasf87/jose-reusable-workflow/.github/workflows/update-changelog.yml@master
    secrets: inherit